development: &default
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: db/production.sqlite3

test: &test
  <<: *default
  database: db/test.sqlite3

cucumber:
  <<: *test
